import React from 'react';

const Header: React.FC = () => {
  return (
    <header>
      <title>プラネタゲームラボ</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </header>
  );
};
export default Header;
