import React, { useState } from 'react';
import { StaticImage } from 'gatsby-plugin-image';

type HeaderProps = {
  sideComponent?: React.ReactNode;
};

const Header: React.FC<HeaderProps> = ({ sideComponent }) => {
  const [isMenuOpened, setIsMenuOpened] = useState(false);

  function menuOpenHandler() {
    setIsMenuOpened(!isMenuOpened);
  }

  return (
    <header>
      <title>プラネタゲームラボ</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />

      <nav className='flex justify-center w-full mb-9 py-4 border-b-2'>
        {/* スマホでのメニューボタン */}
        <div className='fixed right-4 lg:hidden'>
          <button
            className='flex items-center px-3 py-2 border rounded bg-white bg-opacity-60 border-black hover:text-white hover:border-white'
            onClick={menuOpenHandler}
          >
            <svg
              className='fill-current h-3 w-3'
              viewBox='0 0 20 20'
              xmlns='http://www.w3.org/2000/svg'
            >
              <title>メニュー</title>
              <path d='M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z' />
            </svg>
          </button>
        </div>

        <div className='flex flex-1 flex-wrap items-center justify-center lg:justify-start max-w-full lg:flex-nowrap lg:max-w-screen-lg'>
          <div className='flex items-center flex-shrink-0 mr-6'>
            <StaticImage
              className='h-8 w-64 mr-2'
              src='../images/blog_logo_origin.png'
              alt='Logo'
            />
          </div>
          <div
            className={
              'text-center font-bold items-center transition flex-grow w-full fixed top-16 bg-white transpa rounded-xl origin-top text-lg divide-y-2 lg:flex lg:w-auto lg:static lg:bg-transparent lg:rounded-none lg:text-sm lg:divide-y-0 lg:space-x-4' +
              (isMenuOpened ? ' scale-y-100' : ' scale-y-0 lg:scale-y-100')
            }
          >
            <a href='#responsive-header' className='block py-4 lg:inline-block hover:text-white'>
              ゲーム
            </a>
            <a href='#responsive-header' className='block py-4 lg:inline-block hover:text-white'>
              記事
            </a>
            <a href='#responsive-header' className='block py-4 lg:inline-block hover:text-white '>
              その他
            </a>
            <a href='#responsive-header' className='block py-4 lg:inline-block hover:text-white'>
              関連サイト
            </a>
            <a href='#responsive-header' className='block py-4 lg:inline-block hover:text-white'>
              コンタクト
            </a>
          </div>
        </div>
      </nav>
    </header>
  );
};
export default Header;
